version: "3.7"

services:
  frontend:
    build:
      dockerfile: docker/frontend.dockerfile
      context: .

  backend:
    build:
      dockerfile: docker/backend.dockerfile
      context: .
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
