version: "3.7"

services:
  frontend:
    build:
      dockerfile: docker/frontend.dockerfile
      context: .

  backend:
    build:
      dockerfile: docker/backend.dockerfile
      context: .
    depends_on:
      - mysql

  migrator:
    build:
      dockerfile: docker/backend.dockerfile
      context: .
    depends_on:
      - mysql
    command:
      - flask
      - db
      - upgrade

  mysql:
    image: mysql:5
    restart: always
