version: "3.7"

services:
  nginx:
    container_name: evc_nginx
    image: nginx
    volumes:
      - "${PWD}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

  frontend:
    container_name: evc_front
    build:
      dockerfile: docker/frontend.dockerfile
      context: .

  backend:
    container_name: evc_back
    build:
      dockerfile: docker/backend.dockerfile
      context: .
    depends_on:
      - mysql
    ports:
      - 5000:80
  migrator:
    build:
      dockerfile: docker/backend.dockerfile
      context: .
    depends_on:
      - mysql
    command:
      - flask
      - db
      - upgrade

  mysql:
    container_name: evc_mysql
    image: mysql:5
    restart: always
