"""song relationship

Revision ID: 13e720743b24
Revises: 6da7e137fe0e
Create Date: 2020-04-09 22:08:43.519508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e720743b24'
down_revision = '6da7e137fe0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'vote_song', 'song', ['song_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote_song', type_='foreignkey')
    # ### end Alembic commands ###
