"""songs table

Revision ID: 24d55cf1a96f
Revises: 
Create Date: 2020-03-26 18:24:16.680439

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '24d55cf1a96f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('song',
                            sa.Column('id', sa.String(36), primary_key=True, unique=True, nullable=False),
                            sa.Column('title', sa.String(length=120), nullable=False),
                            sa.Column('artist', sa.String(length=60), nullable=False),
                            sa.Column('country', sa.String(length=16), nullable=False),
                            sa.Column('link', sa.Text(), nullable=False),
                            sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###

    op.bulk_insert(table,
                   [
                       {"id": "c7c3c7b0-b390-49db-bb55-c6914e535cfb", "title": "Sandro", "artist": "Running", "country": "Cyprus", "link": "https://www.youtube.com/watch?v=Jl_qEw_4OK0&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=21"},
                       {"id": "7ec0d9bf-fd9e-4fd0-906c-6e122ee0003e", "title": "Tom Leeb", "artist": "Mon alliée (The Best in Me)", "country": "France", "link": "https://www.youtube.com/watch?v=D02Xlo_LfRU&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=35"},
                       {"id": "1235aa8b-2f52-467f-843b-028f30442eb0", "title": "Ben Dolic", "artist": "Violent Thing", "country": "Germany", "link": "https://www.youtube.com/watch?v=hAobDQ9GbT4&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=31"},
                       {"id": "665624dc-4cc8-4dc6-ab98-dcefcc1d9b72", "title": "Stefania", "artist": "Supergirl", "country": "Greece", "link": "https://www.youtube.com/watch?v=dJxCINWp_j0&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=10"},
                       {"id": "12a523ec-22cb-48e6-b9d2-6f9113d547e2", "title": "Daði og Gagnamagnið", "artist": "Think About Things", "country": "Iceland", "link": "https://www.youtube.com/watch?v=1HU7ocv3S2o&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=18"},
                       {"id": "cb044e8c-3012-46b3-8f30-edb748a40a1a", "title": "Lesley Roy", "artist": "Story of My Life", "country": "Ireland", "link": "https://www.youtube.com/watch?v=HLgE0Ayl5Hc&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=24"},
                       {"id": "b2a939ae-0bbc-4ae7-8a8c-73a20e85ea7a", "title": "Diodato", "artist": "Fai Rumore", "country": "Italy", "link": "https://www.youtube.com/watch?v=TA57rugucwk&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=3"},
                       {"id": "b5270707-f6db-400d-a19f-155441fadfd0", "title": "Roxen", "artist": "Alcohol You", "country": "Romania", "link": "https://www.youtube.com/watch?v=TmqSU3v_Mtw&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=7"},
                       {"id": "ae846dc3-a25e-48a8-86f6-b4eafdd92f70", "title": "Blas Cantó", "artist": "Universo", "country": "Spain", "link": "https://www.youtube.com/watch?v=zuDdex1st-Y&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=38"},
                       {"id": "e5153106-49de-453c-a05e-628b13439f50", "title": "James Newman", "artist": "My Last Breath", "country": "United Kingdom", "link": "https://www.youtube.com/watch?v=6iS-lV909T4&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=36"},
                   ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###


