"""base

Revision ID: 6da7e137fe0e
Revises: 
Create Date: 2020-04-09 21:24:01.340145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da7e137fe0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    songs = op.create_table('song',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('artist', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=16), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('validation', sa.String(length=36), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('validation')
    )
    op.create_table('vote_song',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ),
    sa.PrimaryKeyConstraint('vote_id', 'song_id', 'position')
    )
    op.create_index(op.f('ix_vote_song_song_id'), 'vote_song', ['song_id'], unique=False)
    op.create_index(op.f('ix_vote_song_vote_id'), 'vote_song', ['vote_id'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(songs,
                   [
                       {"artist": "Sandro", "title": "Running", "country": "Cyprus", "link": "https://www.youtube.com/watch?v=Jl_qEw_4OK0&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=21"},
                       {"artist": "Tom Leeb", "title": "Mon Alliée (The Best in Me)", "country": "France", "link": "https://www.youtube.com/watch?v=J5SOdhXjYko&list=RDJ5SOdhXjYko&start_radio=1&t=6"},
                       {"artist": "Ben Dolic", "title": "Violent Thing", "country": "Germany", "link": "https://www.youtube.com/watch?v=hAobDQ9GbT4&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=31"},
                       {"artist": "Stefania", "title": "Supergirl", "country": "Greece", "link": "https://www.youtube.com/watch?v=dJxCINWp_j0&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=10"},
                       {"artist": "Daði og Gagnamagnið", "title": "Think About Things", "country": "Iceland", "link": "https://www.youtube.com/watch?v=1HU7ocv3S2o&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=18"},
                       {"artist": "Lesley Roy", "title": "Story of My Life", "country": "Ireland", "link": "https://www.youtube.com/watch?v=HLgE0Ayl5Hc&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=24"},
                       {"artist": "Diodato", "title": "Fai Rumore", "country": "Italy", "link": "https://www.youtube.com/watch?v=TA57rugucwk&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=3"},
                       {"artist": "Roxen", "title": "Alcohol You", "country": "Romania", "link": "https://www.youtube.com/watch?v=TmqSU3v_Mtw&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=7"},
                       {"artist": "Blas Cantó", "title": "Universo", "country": "Spain", "link": "https://www.youtube.com/watch?v=zuDdex1st-Y&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=38"},
                       {"artist": "James Newman", "title": "My Last Breath", "country": "United Kingdom", "link": "https://www.youtube.com/watch?v=6iS-lV909T4&list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y&index=36"},
                       {"artist": "Erin Mai", "title": "Calon Yn Curo", "country": "Wales", "link": "https://www.youtube.com/watch?v=jNS2_eOFeD8"},
                   ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_song_vote_id'), table_name='vote_song')
    op.drop_index(op.f('ix_vote_song_song_id'), table_name='vote_song')
    op.drop_table('vote_song')
    op.drop_table('vote')
    op.drop_table('song')
    # ### end Alembic commands ###
