"""added validation field to votes

Revision ID: b2d712961ecb
Revises: e2141e97ecc8
Create Date: 2020-04-09 15:00:32.883730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d712961ecb'
down_revision = 'e2141e97ecc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('validation', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'vote', ['validation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='unique')
    op.drop_column('vote', 'validation')
    # ### end Alembic commands ###
